# Generated by Django 4.2.2 on 2023-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
            ],
        ),
    ]
