# Generated by Django 4.2.2 on 2023-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='game_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
