# Generated by Django 4.2.2 on 2023-07-11 03:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='demo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='demo', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='minimum',
            new_name='pc_minimum',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='recommended',
            new_name='pc_recommended',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='background',
            field=models.ImageField(default='default.jgp', upload_to=''),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='background_raw',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='controller_support',
            field=models.CharField(default='demo'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='dlc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='linux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='mac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='movies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='recommendations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='release_date',
            field=models.CharField(default='demo'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='screenshots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='support_email',
            field=models.CharField(default='demo'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='support_url',
            field=models.CharField(default='demo'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='windows',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='metacritic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='supported_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
        migrations.AddField(
            model_name='gamegenre',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.gameinfo'),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.gameinfo'),
        ),
    ]
