# Generated by Django 4.2.2 on 2023-06-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_gameinfo_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='game_id',
            new_name='id',
        ),
    ]
