# Generated by Django 4.2.2 on 2023-07-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_game_id_gameinfo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='game_name',
            new_name='name',
        ),
    ]
