# Generated by Django 4.2.2 on 2023-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_game_name_gameinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
