# Generated by Django 4.2.2 on 2023-07-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
